spring:
  application:
    name: mybatis-springboot-demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.202.44.200:3308/atp?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: atp
    password: 'atp#pwd789'
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 20
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml

# 日志相关配置
logging:
  file: ${spring.application.name}
  level:
    ROOT: INFO
    hdli.mapper: debug
  #config: classpath:logback-spring.xml


