spring:
  application:
    name: mybatis-springboot-demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://172.16.255.139:3306/study
    username: root
    password: '123456'
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 20
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml

# 日志相关配置
logging:
  file: ${spring.application.name}
  level:
    ROOT: INFO
    hdli.mapper: debug
  #config: classpath:logback-spring.xml


